language: ruby
cache: bundler
bundler_args: --without yard guard benchmarks
script: "bundle exec rake ci:metrics"
rvm:
  - '1.9'
  - '2.0'
  - '2.1'
  - jruby
  - rbx
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS="$JRUBY_OPTS --debug --1.9"
    - rvm: jruby
      env: JRUBY_OPTS="$JRUBY_OPTS --debug --2.0"
